#security:
#  oauth2:
#    client:
#      client-id: liwei
#      client-secret: wwwliwei001com
#      scope: admin
#      auto-approve-scopes: '.*'
#      authorized-grant-types: client_credentials
#      grant-type: client_credentials
server:
  port: 1090
spring:
  datasource:
    url: jdbc:mysql://106.15.185.93:3306/clouddb01?useSSL=false
    username: root
    password: happyforeversy.
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource #SpringBoot2.0开始将Hikari作为默认连接池
  application:
    name: OAuth20Server
eureka:
  client:
    service-url:
      defaultZone: http://liwei:wwwliwei001com@106.12.19.58:2080/eureka
#        defaultZone: http://liwei:wwwliwei001com@localhost:2080/eureka
mybatis:
  mapper-locations: classpath:mapper/*.xml #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.oauth2authserver.vo # 注意：对应实体类的路径